name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-runner:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v5
      with:
        push: false
        context: .
        file: ./.github/images/main/Dockerfile
        tags: custom-runner-image


  build:
    runs-on: self-hosted
    container: node:18-bookworm
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        which node
        node -v
        yarn
        yarn build:backend
        yarn build-image

  publish:
    runs-on: self-hosted
    needs: [build]
    if: github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v3
    - name: Publish Docker Image
      run:
        echo "Haha"
